export const hotelTypes = [
    "Hotel",
    "Bed & Breakfast",
    "Guest House",
    "Hostel",
    "Inn",
    "Resort",
    "Motel",
    "Apartment",
    "Villa",
    "Cottage",
    "House",
    "Castle",
    "Dorm",
    "Treehouse",
    "Boat",
    "Plane",
    "Camper/RV",
    "Tent",
    "Campsite",
    "Igloo",
    "Hut",
    "Cave",
    "Island",
    "Chalet",
    "Train",
    "Tipi",
    "Casa Particular",
    "Yurt",
    "Pension",
    "Cabin",
    "Bungalow",
    "Barn",
    "Lighthouse",
    "Townhouse",
    "Bus",
]

export const hotelFacilities = [
    "Wi-Fi",
    "Parking",
    "Airport Shuttle",
    "Swimming Pool",
    "Spa",
    "Fitness Center",
    "Non-smoking Rooms",
    "Family Rooms",
    "Pet Friendly",
    "Bar",
    "Restaurant",
    "Room Service",
    "Facilities for Disabled Guests",
    "24-hour Front Desk",
    "Garden",
    "Terrace",
    "Elevator",
    "Express Check-in/Check-out",
    "Safety Deposit Box",
    "Currency Exchange",
    "Tour Desk",
    "Ticket Service",
    "Luggage Storage",
    "Concierge Service",
    "Private Check-in/Check-out",
    "Lockers",
    "Shared Lounge/TV Area",
    "Laundry",
    "Dry Cleaning",
    "Ironing Service",
    "Shoeshine",
    "Daily Maid Service",
    "Meeting/Banquet Facilities",
    "Business Center",
    "Fax/Photocopying",
    "Gift Shop",
    "VIP Room Facilities",
    "Bridal Suite",
    "Newspapers",
    "Safety Deposit Box",
    "Shops (on site)",
    "Mini-market on site",
    "Non-smoking throughout",
    "Air Conditioning",
    "Designated Smoking Area",
    "Heating",
    "Car Hire",
    "Bicycle Rental",
    "Shuttle Service (surcharge)",
    "Airport Shuttle (surcharge)",
    "Shared Kitchen",
    "Library",
    "Sun Terrace",
    "Games Room",
    "Chapel/Shrine",
    "Children's Playground",
    "Karaoke",
    "Nightclub/DJ",
    "Evening Entertainment",
    "Board Games/Puzzles",
    "Books, DVDs, Music for Children",
    "Indoor Play Area",
    "Kids' Outdoor Play Equipment",
    "Baby Safety Gates",
    "Children Television Networks",
    "Casino",
    "Tennis Court",
    "Golf Course (within 3 km)",
    "Fishing",
    "Skiing",
    "Billiards",
    "Table Tennis",
    "Darts",
    "Canoeing",
    "Hiking",
    "Cycling",
    "Bowling",
    "Diving",
    "Horse Riding",
    "Snorkelling",
    "Water Park",
    "Water Sport Facilities (on site)",
]